"""add drivers vehicles, delivery capacity fields

Revision ID: 04ad4e39d2a5
Revises: 97af82024158
Create Date: 2026-07-17 23:09:13.398283+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ad4e39d2a5'
down_revision: Union[str, None] = '97af82024158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('weight_kg', sa.Float(), server_default='0', nullable=False))
    op.add_column('deliveries', sa.Column('volume_m3', sa.Float(), server_default='0', nullable=False))
    op.add_column('drivers', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('drivers', sa.Column('working_hours_start', sa.Time(), nullable=False))
    op.add_column('drivers', sa.Column('working_hours_end', sa.Time(), nullable=False))
    op.add_column('drivers', sa.Column('break_start', sa.Time(), nullable=True))
    op.add_column('drivers', sa.Column('break_end', sa.Time(), nullable=True))
    op.add_column('drivers', sa.Column('max_working_minutes', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('plate_number', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('capacity_weight_kg', sa.Float(), nullable=False))
    op.add_column('vehicles', sa.Column('capacity_volume_m3', sa.Float(), nullable=False))
    op.add_column('vehicles', sa.Column('driver_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['id'])
    op.drop_column('vehicles', 'license_plate')
    op.drop_column('vehicles', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('license_plate', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'driver_id')
    op.drop_column('vehicles', 'capacity_volume_m3')
    op.drop_column('vehicles', 'capacity_weight_kg')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'plate_number')
    op.drop_column('drivers', 'max_working_minutes')
    op.drop_column('drivers', 'break_end')
    op.drop_column('drivers', 'break_start')
    op.drop_column('drivers', 'working_hours_end')
    op.drop_column('drivers', 'working_hours_start')
    op.drop_column('drivers', 'status')
    op.drop_column('deliveries', 'volume_m3')
    op.drop_column('deliveries', 'weight_kg')
    # ### end Alembic commands ###
