"""add status to route stops

Revision ID: de714869c911
Revises: 67afb57ca5eb
Create Date: 2026-07-18 11:59:43.814179+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de714869c911'
down_revision: Union[str, None] = '67afb57ca5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'route_stops',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_stops', 'status')
    # ### end Alembic commands ###
