"""add depots, extend routes and route_stops

Revision ID: 67afb57ca5eb
Revises: 04ad4e39d2a5
Create Date: 2026-07-17 23:40:39.066440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67afb57ca5eb'
down_revision: Union[str, None] = '04ad4e39d2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('estimated_arrival', sa.Time(), nullable=False))
    op.add_column('route_stops', sa.Column('estimated_departure', sa.Time(), nullable=False))
    op.add_column('route_stops', sa.Column('distance_from_previous_km', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('vehicle_id', sa.Uuid(), nullable=True))
    op.add_column('routes', sa.Column('depot_id', sa.Uuid(), nullable=False))
    op.add_column('routes', sa.Column('return_to_depot', sa.Boolean(), nullable=False))
    op.add_column('routes', sa.Column('total_distance_km', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('total_duration_minutes', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'routes', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'depots', ['depot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'total_duration_minutes')
    op.drop_column('routes', 'total_distance_km')
    op.drop_column('routes', 'return_to_depot')
    op.drop_column('routes', 'depot_id')
    op.drop_column('routes', 'vehicle_id')
    op.drop_column('route_stops', 'distance_from_previous_km')
    op.drop_column('route_stops', 'estimated_departure')
    op.drop_column('route_stops', 'estimated_arrival')
    # ### end Alembic commands ###
